#' @importFrom data.table data.table setnames setkey setcolorder setorder tstrsplit CJ .N .SD .EACHI :=
#' @import ggplot2
#' @import ggrepel
#' @importFrom dplyr %>% count rename filter_all all_vars
#' @import corrplot
#' @import rlist
#' @import EnhancedVolcano
#' @import fitdistrplus


#' @title bam2count
#' @description Function to generate a read counts table from bam files
#' @param bamfolder Path to the folder containing bam files (one bam file per sample is expected)
#' @param annotation Annotation data table produced by \code{\link{read_annotation}} listing transcript names and lengths of their 5'UTR, CDS and 3'UTR segments.
#' It has five columns: transcript, l_tr, l_utr5, l_cds and l_utr3.
#' Transcript names and segment lengths must correspond to the reference sequences to which the reads were mapped.
#' @details This function is designed for bam files generated by mapping to a transcriptome (not a genome).
#' For each sample, it counts the number of reads mapping to different chromosomes (the 'seqname' bam field).
#' Annotation must be provided to ensure a complete transcript list, including those with zero counts.
#' Low count transcripts can be filtered out later using the \code{\link{min_count_filter}} function.
#' RNA and RPF bam files can be placed in the same folder and imported together using this function if CELP bias correction on RPF counts is not desired.
#' If CELP correction is desired, RNA and RPF bams should be placed in separate folders.
#' RNA bams should be imported using this function; RPF bams should be imported using the \code{\link{bamtolist_rW}} function following the CELP workflow.
#' @return A data frame where the first column contains transcript IDs and the remaining columns contain read counts in imported samples.
#' @examples
#' rna_count_LMCN <- bam2count(bamfolder = "./Data/Bam/RNA", annotation = annotation_human_cDNA)
#' rpf_count_LMCN <- bam2count(bamfolder = "./Data/Bam/RPF", annotation = annotation_human_cDNA)
#' @export
bam2count <- function(bamfolder, annotation){
  annotation_tr <- as.data.frame(annotation$transcript)
  names(annotation_tr) <- "transcript"
  names <- list.files(path = bamfolder, pattern = ".bam$")
  counts_list <- list()
  counts_list[["annotation"]] <- annotation_tr
  for (n_i in names){
    filename <- paste(bamfolder, n_i, sep = "/")
    bam_i <- GenomicAlignments::readGAlignments(filename)
    counts_i <- as.data.frame(bam_i) %>% dplyr::count(seqnames)
    sample_name_i <- unlist(strsplit(n_i, ".bam"))
    names(counts_i) <- c("transcript", sample_name_i)
    counts_list[[sample_name_i]] <- counts_i
  }
  counts_df <- Reduce(function(x, y) merge(x, y, by = "transcript", all=TRUE), counts_list)
  counts_df[is.na(counts_df)] <- 0
  return(counts_df)
}


#' @title gm_mean_z
#' @description Function to calculate geometric mean of a vector of non-negative numbers
#' @details Zeros will remain in the calculation and render the geometric mean zero.
#' Compare with \code{\link{gm_mean}}.
#' @param x Vector of non-negative numbers (may include zero)
#' @return Geometric mean
#' @export
gm_mean_z <- function(x){
  exp(sum(log(x)) / length(x))
}


#' @title gm_mean
#' @description Function to calculate geometric mean of positive numbers in a vector
#' @details Zeros and negative numbers will be effectively treated as 1:
#' They will not contribute to the product of numbers but will be included in calculation of vector length.
#' Compare with \code{\link{gm_mean_z}}.
#' @param x A vector of numbers (may include zero or negative numbers)
#' @param na.rm Whether to remove \code{NA} values before summing. Default: \code{TRUE}.
#' @return Geometric mean of the vector with the zeros and negative numbers replaced by 1
#' @export
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}


#' @title normalize_median_of_ratios_append
#' @description Function to normalize a RNA-seq or ribo-seq dataset for library size variation
#' @details The original data columns are retained and normalized columns are added.
#' Compare with \code{\link{normalize_median_of_ratios}}.
#'
#' Use the \code{data_columns} argument to exclude gene or transcript ID and other metadata columns from the
#' calculations, and, to normalize RNA and RPF counts separately while keeping them in the same data frame.
#' @param expression_data_frame A data frame containing RNA-seq, ribo-seq or similar data.
#' Rows are genes/transcripts and columns are samples.
#' The data frame may contain additional columns for gene/transcript ID or other metadata.
#' @param data_columns A vector of numbers specifying the columns to be normalized together.
#' @return An augmented data frame with all the original columns retained and normalized columns
#' appended to the end. New columns are named 'norm.<old_column>'.
#' @examples
#' rna_observed_normalized_LMCN <- normalize_median_of_ratios_append(rna_rpf_count_LMCN, c(2:9))
#' @export
normalize_median_of_ratios_append <- function (expression_data_frame, data_columns){
  gm_mean_z <- function(x){
    exp(sum(log(x)) / length(x))
  }
  edf <- expression_data_frame
  geo.mean.vec <- apply(edf[,data_columns], 1, function(x) gm_mean_z(x))
  ratios.df <- edf[,data_columns]/geo.mean.vec
  # Division by 0 gm_mean creates NAs here.
  normalization.factors <- apply(ratios.df, 2, function(x) median(x, na.rm=TRUE))
  # NAs are removed from calculation of median here.
  print("Normalization factors:")
  print(normalization.factors)
  normalized.edf <- t(t(edf[,data_columns])/normalization.factors)
  colnames(normalized.edf) <- paste0("norm.", colnames(normalized.edf))
  combined.df <- data.frame(edf,normalized.edf)
  return(combined.df)
}


#' @title normalize_median_of_ratios
#' @description Function to normalize a RNA-seq or ribo-seq dataset for library size variation
#' @details The original columns of non-normalized counts are replaced in situ with normalized counts.
#' Compare with \code{\link{normalize_median_of_ratios_append}}.
#'
#' Use the \code{data_columns} argument to exclude gene or transcript ID and other metadata columns from the
#' calculations, and, to normalize RNA and RPF counts separately while keeping them in the same data frame.
#' @param expression_data_frame A data frame containing RNA-seq, ribo-seq or similar data.
#' Rows are genes/transcripts and columns are samples.
#' The data frame may contain additional columns for gene/transcript ID or other metadata.
#' @param data_columns A vector of numbers specifying the columns to be normalized together.
#' @return A data frame the same size as the input data frame where non-normalized counts in the 'data_columns'
#' are replaced in situ by normalized counts. Column names are not changed.
#' @examples
#' # The data set rna_CELP_rpf_count_LMCN contains 17 columns: [1] transcript [2:9] RNA counts [10:17] RPF counts.
#' # RNA and RPF counts are normalized separately.
#' rna_CELP_rpf_count_norm1_LMCN <- Ribolog::normalize_median_of_ratios(rna_CELP_rpf_count_LMCN, c(2:9))
#' rna_CELP_rpf_count_norm2_LMCN <- Ribolog::normalize_median_of_ratios(rna_CELP_rpf_count_norm1_LMCN, c(10:17))
#' @export
normalize_median_of_ratios <- function (expression_data_frame, data_columns){

  if (length(data_columns) < 2){
      print('Skipped Normalisation because less than two data columns specified.')
      return(expression_data_frame)
  }

  gm_mean_z <- function(x){
    exp(sum(log(x)) / length(x))
  }
  edf <- expression_data_frame
  id.names <- names(edf)
  geo.mean.vec <- apply(edf[,data_columns], 1, function(x) gm_mean_z(x))
  ratios.df <- edf[,data_columns]/geo.mean.vec
  # Division by 0 gm_mean will create NAs here.
  normalization.factors <- apply(ratios.df, 2, function(x) median(x, na.rm=TRUE))
  # NAs will be removed from calculation of median here.
  print("Normalization factors:")
  print(normalization.factors)
  normalized.edf <- t(t(edf[,data_columns])/normalization.factors)
  edf[, data_columns] <- normalized.edf
  names(edf) <- id.names
  return(edf)
}



#' @title min_count_filter
#' @description Function to filter out genes with counts below a minimum in one or more samples.
#' @param x Input data frame containing RNA-seq or Ribo-seq data.
#' Rows are genes/transcripts and columns are samples.
#' The data.frame may contain additional columns for gene/transcript ID or other metadata.
#' @param mincount A single number (float), minimum RNA or RPF count required for a gene/transcript to be retained.
#' @param columns A vector specifying the columns to be considered for minimum count filtering.
#' @param method The method of filtering. Options: \code{"all", "average"}. Default: \code{"all"}.
#' @details If \code{method="all"} is chosen, a gene passes the filtering only if all samples specified
#' by the \code{columns} argument have values \code{>= mincount}. If \code{method="average"} is chosen, a gene
#' passes the filtering if the average count among the specified \code{columns} is \code{>= mincount}.
#'
#' Use the \code{columns} argument to exclude gene/transcript ID and other metadata columns from the
#' calculations or to filter RNA and RPF counts separately while keeping them in the same data.frame.
#' @return Filtered data frame containing all the original columns but only the rows (genes)
#' that pass the filtering criterion.
#' @examples
#' rr_LMCN.v1 <- min_count_filter(rr_LMCN, mincount = 5, columns = c(2:9), method = "all")
#' rr_LMCN.v2 <- min_count_filter(rr_LMCN.v1, mincount = 2, columns = c(10:17), method = "average")
#' @export
min_count_filter <- function(x, mincount, columns, method="all"){
  if (method=="all"){
    x <- x[!rowSums(x[,columns] < mincount),]
  } else if (method=="average"){
    x <- x[rowMeans(x[,columns]) >= mincount,]
  }
  return(x)
}


#' @title CELP_detect_bias
#' @description Function to compute codon-level stalling bias coefficients using the CELP (Consistent Excess of Loess Preds) method
#' @param tr_codon_read_count_list A list generated by \code{\link{psite_to_codon_count}}
#' containing observed read counts per codon per trancript per sample.
#' @param codon_raduis Number of codons on either side of each codon influencing the loess prediction for the middle codon. Default: 5.
#' @param loess_method Determines whether the fitted surface should be computed exactly ("direct") or via interpolation from a kd tree ("interpolate").
#' A third option is "none" which means than raw observed counts to calculate the bias coefficient (no loess). Default: "interpolate".
#' @details This function starts with running a loess curve on per-codon read counts along the transcript to borrow information
#' from neighboring codons mitigating the uncertainty of p-site offset assignment and experimental stochasticity.
#' Loess span parameter is calculated from the user-defined codon radius and CDS length.
#' Then, a bias coefficient is calculated for each codon by integrating information on the excess of loess-predicted
#' read counts at that codon comapred to the transcript's background across all samples. Finally, loess predicted counts
#' read counts are divided by bias coefficients to calculate bias-corrected counts.
#' The "direct" fitting method takes longer to complete but does not run into kd-tree-related memory issues.
#' The loess_method "none" option is included mainly to enable comparison and show effectiveness of using loess in
#' finding bona fide bias positions. It is NOT recommended for actual bias detection.
#' @return A list of data frames (one per transcript) containing codon-level bias coefficients.
#' It has the following structure: list$<transcript.ID> data.frame: [1] codon_number [2] codon_type [3] aa_type [4] bias_coefficient.
#' @examples
#' bias_coeff_list_LMCN_noloess <- CELP_detect_bias(tr_codon_read_count_LMCN, loess_method = "none")
#' bias_coeff_list_LMCN_withloess <- CELP_detect_bias(tr_codon_read_count_LMCN, loess_method = "interpolate")
#' @export
CELP_detect_bias <- function(tr_codon_read_count_list, loess_method = "interpolate", codon_raduis = 5){

  x <- tr_codon_read_count_list
  bias_coefficients_list <- list()
  sample_names_i <- names(x)
  tr_names_i <- names(x[[1]])

  # Run loess and compute loess predicted values
  for (t in tr_names_i){
    if (loess_method == "none"){
      for (s in sample_names_i){
        x[[s]][[t]]$excess_ratio <- x[[s]][[t]]$observed_count / median(x[[s]][[t]]$observed_count[x[[s]][[t]]$observed_count>0])
      }
    } else {
      l_cds <- dim(x[[1]][[t]])[1]
      span_tr <- (2 * codon_raduis + 1) / l_cds
      for (s in sample_names_i){
        x[[s]][[t]]$loess_pred <- suppressWarnings(predict(loess(x[[s]][[t]]$observed_count ~ x[[s]][[t]]$codon_number, span = span_tr, se = FALSE, control = loess.control(surface = loess_method))))
        x[[s]][[t]]$loess_pred [x[[s]][[t]]$loess_pred < 0 ] <- 0
        x[[s]][[t]]$excess_ratio <- x[[s]][[t]]$loess_pred / median(x[[s]][[t]]$loess_pred[x[[s]][[t]]$loess_pred>0])
      }
    }
  }

  # Calculate position-specific bias coefficients
  for (t in tr_names_i){
    bias_coefficients_list[[t]] <- data.frame(codon_number = x[[1]][[t]]$codon_number, codon_type = x[[1]][[t]]$codon_type, aa_type = x[[1]][[t]]$aa_type)
    for (s in sample_names_i){
      bias_coefficients_list[[t]] <- data.frame(bias_coefficients_list[[t]], x[[s]][[t]]$excess_ratio)
    }
    names(bias_coefficients_list[[t]]) <- c("codon_number", "codon_type", "aa_type", sample_names_i)
    bias_coefficient <- apply(bias_coefficients_list[[t]][,-c(1:3)], 1, function(y) gm_mean(y))
    bias_coefficients_list[[t]] <- data.frame(bias_coefficients_list[[t]][,c(1:3)], bias_coefficient)
  }
  return(bias_coefficients_list)
}


#' @title CELP_bias
#' @description Function to compute codon-level stalling bias coefficients and bias-corrected read counts using the CELP (Consistent Excess of Loess Preds) method
#' @param tr_codon_read_count_list A list generated by \code{\link{psite_to_codon_count}}
#' containing observed read counts per codon per trancript per sample.
#' @param codon_raduis Number of codons on either side of each codon influencing the loess prediction for the middle codon. Default: 5.
#' @param loess_method Determines whether the fitted surface should be computed exactly ("direct") or via interpolation from a kd tree ("interpolate"). Default: "interpolate".
#' @param gini_moderation Logical argument. If set to TRUE, (bias_coefficient)^(gini_index) is used as correction factor.
#' If set to FALSE, bias_coefficient is used as correction factor. Default: FALSE.
#' @details This function is the heart of CELP method for stalling bias detection and correction.
#' It starts with running a loess curve on per-codon read counts along the transcript to borrow information
#' from neighboring codons mitigating the uncertainty of p-site offset assignment and experimental stochasticity.
#' Loess span parameter is calculated from the user-defined codon radius and CDS length.
#' Then, a bias coefficient is calculated for each codon by integrating information on the excess of loess-predicted
#' read counts at that codon comapred to the transcript's background across all samples. Finally, loess predicted counts
#' read counts are divided by bias coefficients to calculate bias-corrected counts.
#' The "direct" fitting method takes longer to complete but does not run into kd-tree-related memory issues.
#' Gini index for each transcript is calculated from the bias coefficients of all of its codons.
#' Gini moderation ensures that the strength of bias correction is proportional to the original level of heterogenity in read distribution along the transcript.
#' @return A list composed of two lists: 1. bias coefficients 2. bias-corrected read counts
#' The bias coefficient list has the following structure: list$<transcript.ID> data.frame: [1] codon_number [2] codon_type [3] aa_type [4] bias_coefficient.
#' The bias-corrected read count list has the following structure: list$<sample.name>$<transcript.ID> data.frame:
#' [1] codon_number [2] codon_type [3] aa_type [4] observed_count [5] bias_coefficient [6] corrected_count.
#' Gini moderation ensures that the strength of correction is proportional to the original level of heterogenity in read distribution along the transcript.
#' @examples
#' tr_codon_bias_coeff_corrected_count_LMCN <- CELP_bias(tr_codon_read_count_LMCN)
#' tr_codon_bias_coeff_corrected_count_LMCN_gini_moderated <- CELP_bias(tr_codon_read_count_LMCN, gini_moderation = TRUE)
#' tr_codon_bias_coeff_corrected_count_LMCN_direct_fit <- CELP_bias(tr_codon_read_count_LMCN, loess_method = "direct")
#' @export
CELP_bias <- function(tr_codon_read_count_list, codon_raduis = 5, loess_method = "interpolate", gini_moderation = FALSE){

  tr_codon_read_count_loess_corrected <- tr_codon_read_count_list
  bias_coefficients_list <- list()
  sample_names_i <- names(tr_codon_read_count_loess_corrected)
  tr_names_i <- names(tr_codon_read_count_loess_corrected[[1]])

  # Run loess and compute loess predicted values
  for (t in tr_names_i){
    l_cds <- dim(tr_codon_read_count_loess_corrected[[1]][[t]])[1]
    span_tr <- (2*codon_raduis+1)/l_cds
    for (s in sample_names_i){
      tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred <-
        suppressWarnings(predict(loess(tr_codon_read_count_loess_corrected[[s]][[t]]$observed_count ~ tr_codon_read_count_loess_corrected[[s]][[t]]$codon_number, span = span_tr, se = FALSE, control = loess.control(surface = loess_method))))
      tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred [tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred < 0 ] <- 0
      tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred_by_nz_median <-
        tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred / median(tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred[tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred>0])
    }

    # Calculate position-specific bias coefficients
    bias_coefficients_list[[t]] <- data.frame(codon_number = tr_codon_read_count_loess_corrected[[1]][[t]]$codon_number,
                                              codon_type = tr_codon_read_count_loess_corrected[[1]][[t]]$codon_type,
                                              aa_type = tr_codon_read_count_loess_corrected[[1]][[t]]$aa_type)
    for (s in sample_names_i){
      bias_coefficients_list[[t]] <- data.frame(bias_coefficients_list[[t]], tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred_by_nz_median)
    }
    names(bias_coefficients_list[[t]]) <- c("codon_number", "codon_type", "aa_type", sample_names_i)
    bias_coefficient <- apply(bias_coefficients_list[[t]][,-c(1:3)], 1, function(y) gm_mean(y))
    bias_coefficient_gini <- DescTools::Gini(bias_coefficient)
    bias_coefficients_list[[t]] <- data.frame(bias_coefficients_list[[t]][,c(1:3)], bias_coefficient)

    # calculate bias-corrected read counts
    for (s in sample_names_i){
      tr_codon_read_count_loess_corrected[[s]][[t]]$bias_coefficient <- bias_coefficients_list[[t]]$bias_coefficient
      if (gini_moderation == TRUE){
        correction_power <- bias_coefficient_gini
      } else{
        correction_power <- 1
      }
      tr_codon_read_count_loess_corrected[[s]][[t]]$corrected_count <-
        tr_codon_read_count_loess_corrected[[s]][[t]]$loess_pred / (tr_codon_read_count_loess_corrected[[s]][[t]]$bias_coefficient)^correction_power
      tr_codon_read_count_loess_corrected[[s]][[t]] <- subset(tr_codon_read_count_loess_corrected[[s]][[t]], select = -c(loess_pred, loess_pred_by_nz_median))
    }
  }

  output <- list(bias_coefficients_list = bias_coefficients_list, tr_codon_read_count_loess_corrected = tr_codon_read_count_loess_corrected)
  return(output)
}


#' @title amino_acid_names
#' @description Lookup table mapping the single-letter amino acid codes found in the \code{aa_type}
#' column produced by \code{\link{psite_to_codon_count}}, \code{\link{CELP_detect_bias}} and
#' \code{\link{CELP_bias}} (derived from \code{Biostrings::GENETIC_CODE}, with stop codons coded as "X")
#' to full amino acid names, for readable labels in \code{\link{get_aa_dwell_time_estimates}} and \code{\link{plot_aa_dwell_times}}.
#' @format A data frame with 21 rows and 2 columns:
#' \describe{
#'   \item{aa_type}{Single-letter amino acid code (standard IUPAC code; "X" denotes a stop codon).}
#'   \item{amino_acid}{Full amino acid name (e.g. "Glycine"); "Stop" for stop codons.}
#' }
#' @export

amino_acid_names <- data.frame(
  aa_type = c("A","R","N","D","C","Q","E","G","H","I","L","K","M","F","P","S","T","W","Y","V","X"),
  amino_acid = c("Alanine","Arginine","Asparagine","Aspartate","Cysteine","Glutamine","Glutamate",
                 "Glycine","Histidine","Isoleucine","Leucine","Lysine","Methionine","Phenylalanine",
                 "Proline","Serine","Threonine","Tryptophan","Tyrosine","Valine","Stop"),
  stringsAsFactors = FALSE
)


#' @title get_codon_bias_coefficients
#' @description Split codon read counts by an arbitrary covariate of interest (e.g. genotype, treatment,
#' any column in a sample attributes/design table), run \code{\link{CELP_detect_bias}} separately within
#' each covariate level, and combine the results into a single long-format data frame ready for per-codon
#' or per-amino-acid ribosome dwell time analysis (see \code{\link{get_codon_dwell_time_estimates}} and \code{\link{get_aa_dwell_time_estimates}}).
#' @param tr_codon_read_count_list A list generated by \code{\link{psite_to_codon_count}} containing
#' observed read counts per codon per transcript per sample (list$<sample.name>$<transcript.ID>).
#' @param sample_attributes A data frame describing sample attributes (one row per sample), analogous to
#' the \code{design} argument used elsewhere in Ribolog (e.g. \code{\link{tr_region_multi_logit}}). Must
#' contain a column identifying each sample (\code{sample_ID}) and a column with the covariate of interest
#' (\code{covariate_name}).
#' @param sample_ID Name of the column in \code{sample_attributes} that matches the sample names in
#' \code{tr_codon_read_count_list} (i.e. \code{names(tr_codon_read_count_list)}) - values in this column
#' must be spelled exactly like those names (e.g. "CN34_r1_rpf"), not e.g. a replicate name lacking the
#' RNA/RPF suffix.
#' @param covariate_name Name of the column in \code{sample_attributes} describing the comparison to test
#' (e.g. "genotype", "treatment") - this can be any covariate the user wants, it is not tied to any
#' specific study or design.
#' @param loess_method Passed to \code{\link{CELP_detect_bias}}. Default: "interpolate".
#' @param codon_raduis Passed to \code{\link{CELP_detect_bias}}. Default: 5.
#' @details
#' Errors immediately and informatively if \code{sample_ID} or \code{covariate_name} do not match a column
#' of \code{sample_attributes}, or if a given level of \code{covariate_name} has no samples in common
#' between \code{sample_attributes[[sample_ID]]} and \code{names(tr_codon_read_count_list)} - a common
#' cause is passing a \code{sample_ID} column whose values don't exactly match the RNA/RPF-suffixed sample
#' names used as list keys in \code{tr_codon_read_count_list}.
#' @return A single data frame (bc_pa_df) with columns transcript, codon_number, codon_type, aa_type,
#' bias_coefficient, and \code{<covariate_name>}, combining every level of the covariate.
#' @examples
#' bc_pa_df <- get_codon_bias_coefficients(tr_codon_read_count, sample_attributes,
#'                             sample_ID = "sample", covariate_name = "genotype")
#' @export

get_codon_bias_coefficients <- function(tr_codon_read_count_list, sample_attributes, sample_ID, covariate_name,
                            loess_method = "interpolate", codon_raduis = 5){
  if (!(sample_ID %in% colnames(sample_attributes))) {
    stop(paste0("sample_ID '", sample_ID, "' is not a column of sample_attributes. Available columns: ",
                paste(colnames(sample_attributes), collapse = ", ")))
  }
  if (!(covariate_name %in% colnames(sample_attributes))) {
    stop(paste0("covariate_name '", covariate_name, "' is not a column of sample_attributes. Available columns: ",
                paste(colnames(sample_attributes), collapse = ", ")))
  }

  levels <- unique(as.character(sample_attributes[[covariate_name]]))

  labeled <- lapply(levels, function(lvl){
    samples_lvl <- as.character(sample_attributes[sample_attributes[[covariate_name]] == lvl, sample_ID])
    samples_lvl <- intersect(samples_lvl, names(tr_codon_read_count_list))

    if (length(samples_lvl) == 0) {
      stop(paste0("No samples found for ", covariate_name, " = '", lvl, "'. Check that sample_ID ('", sample_ID,
                  "') holds values matching names(tr_codon_read_count_list) exactly, e.g.: ",
                  paste(utils::head(names(tr_codon_read_count_list), 3), collapse = ", "), " ..."))
    }

    bias_lvl <- Ribolog::CELP_detect_bias(tr_codon_read_count_list[samples_lvl],
                                           loess_method = loess_method, codon_raduis = codon_raduis)

    df <- dplyr::bind_rows(bias_lvl, .id = "transcript")
    df[[covariate_name]] <- lvl
    df
  })

  bc_pa_df <- dplyr::bind_rows(labeled)
  return(bc_pa_df)
}


#' @title get_codon_dwell_time_estimates
#' @description Calculate per-codon ribosome dwell time estimates and p-values between two levels of a
#' covariate, from a bc_pa_df produced by \code{\link{get_codon_bias_coefficients}}. For each codon type, fits
#' \code{glm(bias_coefficient ~ covariate)} across all transcripts/positions with that codon, and reports
#' the covariate's coefficient (the estimated dwell time shift relative to \code{ref_level}) and its p-value.
#' @param bc_pa_df Data frame produced by \code{\link{get_codon_bias_coefficients}}, with columns codon_type,
#' bias_coefficient, and the covariate column named \code{covariate_name}.
#' @param covariate_name Name of the covariate column in \code{bc_pa_df} to test (e.g. "genotype").
#' Must currently have exactly two levels; one coefficient/p-value is reported per codon.
#' @param ref_level The level of the covariate to use as the reference/baseline (e.g. "wt").
#' @return A data frame with one row per codon type: codon, mean_dwell_time (the covariate's coefficient),
#' and p_val, sorted by descending mean_dwell_time.
#' @examples
#' codon_ests <- get_codon_dwell_time_estimates(bc_pa_df, covariate_name = "genotype", ref_level = "wt")
#' @export

get_codon_dwell_time_estimates <- function(bc_pa_df, covariate_name, ref_level){
  codons <- unique(bc_pa_df$codon_type)
  estimates <- data.frame(codon = character(), mean_dwell_time = numeric(), p_val = numeric())

  for (codon in codons){
    d <- subset(bc_pa_df, codon_type == codon)
    d[[covariate_name]] <- relevel(factor(d[[covariate_name]]), ref = ref_level)
    fit <- glm(as.formula(paste0("bias_coefficient ~ ", covariate_name)), data = d)

    coeff <- unname(fit$coefficients[2])
    pval <- unname(coef(summary(fit))[2, 4])

    estimates <- rbind(estimates, data.frame(codon = codon, mean_dwell_time = coeff, p_val = pval))
  }

  estimates <- estimates[order(-estimates$mean_dwell_time), ]
  rownames(estimates) <- NULL
  return(estimates)
}


#' @title plot_codon_dwell_times
#' @description Bar plot of per-codon mean dwell time estimates produced by \code{\link{get_codon_dwell_time_estimates}}.
#' Codon labels are converted to RNA notation (T -> U). The start codon (AUG) is colored blue and stop
#' codons (UAA, UGA, UAG) are colored dark red on the axis text; bars are labeled "*" where \code{p_val}
#' is below \code{p_cutoff}, "NS" otherwise.
#' @param codon_estimates Data frame produced by \code{\link{get_codon_dwell_time_estimates}} (columns codon, mean_dwell_time, p_val).
#' @param highlight_codons Optional character vector of codons to highlight with a distinct fill color
#' (e.g. the codons decoded by a tRNA of interest). Accepts either T or U notation. Default: none highlighted.
#' @param p_cutoff Significance threshold used to label significant bars "*". Non-significant bars are left
#' unlabeled. Default: 0.05.
#' @param base_size Base font size for the plot theme. Default: 30.
#' @param label_size Font size for the "*" significance labels above each bar. Default: 8.
#' @return A ggplot2 bar plot object.
#' @details
#' Per-codon axis text coloring (AUG/stop codons) uses a vector of colours in a single
#' \code{ggplot2::element_text()} call, which is not officially supported by ggplot2 but works correctly
#' with current ggplot2 versions; the resulting "Vectorized input to element_text()" warning is expected
#' and suppressed.
#' @examples
#' plot_codon_dwell_times(codon_ests, highlight_codons = c('GGU', 'GGG', 'GGA', 'GGC'))
#' @export

plot_codon_dwell_times <- function(codon_estimates, highlight_codons = NULL, p_cutoff = 0.05, base_size = 30,
                                    label_size = 8){
  codon_estimates$codon <- gsub('T', 'U', codon_estimates$codon)
  codon_estimates <- codon_estimates[order(-codon_estimates$mean_dwell_time), ]
  codon_estimates$codon <- factor(codon_estimates$codon, levels = codon_estimates$codon)

  colour_codon <- ifelse(codon_estimates$codon == "AUG", "#104ec1",
                    ifelse(codon_estimates$codon %in% c("UAA", "UGA", "UAG"), "darkred", "gray40"))

  if (is.null(highlight_codons)) {
    fill_group <- rep(TRUE, nrow(codon_estimates))
  } else {
    highlight_codons <- gsub('T', 'U', highlight_codons)
    fill_group <- !(codon_estimates$codon %in% highlight_codons)
  }

  suppressWarnings(
    ggplot2::ggplot(codon_estimates, ggplot2::aes(x = codon, y = mean_dwell_time, fill = fill_group,
                                                   label = ifelse(p_val < p_cutoff, "*", ""))) +
      ggplot2::geom_bar(stat = "identity", alpha = 0.9) +
      ggplot2::geom_text(vjust = 0, size = label_size) +
      ggplot2::guides(fill = "none") +
      ggplot2::theme_bw(base_size = base_size) +
      ggplot2::scale_x_discrete("Codon") +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5, size = base_size * 0.5)) +
      ggplot2::theme(axis.text.x = ggplot2::element_text(colour = colour_codon),
                     panel.grid.major.x = ggplot2::element_blank(), panel.grid.minor.y = ggplot2::element_blank()) +
      ggplot2::scale_y_continuous("Mean Dwell Time Estimate")
  )
}


#' @title get_aa_dwell_time_estimates
#' @description Calculate per-amino-acid ribosome dwell time estimates and p-values between two levels of
#' a covariate, from a bc_pa_df produced by \code{\link{get_codon_bias_coefficients}}. Codons are pooled by the amino
#' acid they encode (bc_pa_df's \code{aa_type} column, from the standard genetic code) and, for each amino
#' acid, \code{glm(bias_coefficient ~ covariate)} is refit across all the pooled positions/transcripts.
#' @param bc_pa_df Data frame produced by \code{\link{get_codon_bias_coefficients}}, with columns aa_type,
#' bias_coefficient, and the covariate column named \code{covariate_name}.
#' @param covariate_name Name of the covariate column in \code{bc_pa_df} to test (e.g. "genotype").
#' Must currently have exactly two levels; one coefficient/p-value is reported per amino acid.
#' @param ref_level The level of the covariate to use as the reference/baseline (e.g. "wt").
#' @return A data frame with one row per amino acid: amino_acid (full name, e.g. "Glycine", from
#' \code{\link{amino_acid_names}}), mean_dwell_time, and p_val, sorted by descending mean_dwell_time.
#' @examples
#' aa_ests <- get_aa_dwell_time_estimates(bc_pa_df, covariate_name = "genotype", ref_level = "wt")
#' @export

get_aa_dwell_time_estimates <- function(bc_pa_df, covariate_name, ref_level){
  aa_types <- unique(bc_pa_df$aa_type)
  estimates <- data.frame(aa_type = character(), mean_dwell_time = numeric(), p_val = numeric())

  for (aa in aa_types){
    d <- subset(bc_pa_df, aa_type == aa)
    d[[covariate_name]] <- relevel(factor(d[[covariate_name]]), ref = ref_level)
    fit <- glm(as.formula(paste0("bias_coefficient ~ ", covariate_name)), data = d)

    coeff <- unname(fit$coefficients[2])
    pval <- unname(coef(summary(fit))[2, 4])

    estimates <- rbind(estimates, data.frame(aa_type = aa, mean_dwell_time = coeff, p_val = pval))
  }

  estimates <- merge(estimates, Ribolog::amino_acid_names, by = "aa_type", all.x = TRUE)
  estimates$aa_type <- NULL
  estimates <- estimates[, c("amino_acid", "mean_dwell_time", "p_val")]
  estimates <- estimates[order(-estimates$mean_dwell_time), ]
  rownames(estimates) <- NULL
  return(estimates)
}


#' @title plot_aa_dwell_times
#' @description Bar plot of per-amino-acid mean dwell time estimates produced by \code{\link{get_aa_dwell_time_estimates}}.
#' Bars are labeled "*" where \code{p_val} is below \code{p_cutoff}, "NS" otherwise.
#' @param aa_estimates Data frame produced by \code{\link{get_aa_dwell_time_estimates}} (columns amino_acid, mean_dwell_time, p_val).
#' @param highlight_aa Optional character vector of amino acid names (e.g. "Glycine") to highlight with a
#' distinct fill color. Default: none highlighted.
#' @param drop_stop Logical, whether to exclude the "Stop" pseudo-amino-acid from the plot. Default: TRUE.
#' @param p_cutoff Significance threshold used to label significant bars "*". Non-significant bars are left
#' unlabeled. Default: 0.05.
#' @param base_size Base font size for the plot theme. Default: 30.
#' @param label_size Font size for the "*" significance labels above each bar. Default: 8.
#' @return A ggplot2 bar plot object.
#' @examples
#' plot_aa_dwell_times(aa_ests, highlight_aa = "Glycine")
#' @export

plot_aa_dwell_times <- function(aa_estimates, highlight_aa = NULL, drop_stop = TRUE, p_cutoff = 0.05, base_size = 30,
                                 label_size = 8){
  if (drop_stop){
    aa_estimates <- aa_estimates[aa_estimates$amino_acid != 'Stop', ]
  }

  aa_estimates <- aa_estimates[order(-aa_estimates$mean_dwell_time), ]
  aa_estimates$amino_acid <- factor(aa_estimates$amino_acid, levels = aa_estimates$amino_acid)

  if (is.null(highlight_aa)) {
    fill_group <- rep(TRUE, nrow(aa_estimates))
  } else {
    fill_group <- !(aa_estimates$amino_acid %in% highlight_aa)
  }

  ggplot2::ggplot(aa_estimates, ggplot2::aes(x = amino_acid, y = mean_dwell_time, fill = fill_group,
                                              label = ifelse(p_val < p_cutoff, "*", ""))) +
    ggplot2::geom_bar(stat = "identity", alpha = 0.9) +
    ggplot2::geom_text(vjust = 0, size = label_size) +
    ggplot2::guides(fill = "none") +
    ggplot2::theme_bw(base_size = base_size) +
    ggplot2::scale_x_discrete("Amino Acid") +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5, size = base_size * 0.5)) +
    ggplot2::theme(panel.grid.major.x = ggplot2::element_blank(), panel.grid.minor.y = ggplot2::element_blank()) +
    ggplot2::scale_y_continuous("Mean Dwell Time Estimate")
}


#' @title codon2transcript
#' @description Function to sum up codon counts per transcript.
#' @param tr_codon_read_count_loess_corrected_list A list of codon level read counts for all samples and transcripts.
#' It is the second element of a tr_codon_bias_coeff_corrected_count object produced by \code{\link{CELP_bias}}.
#' It has the following structure:
#' list$<sample.name>$<transcript.ID> data.frame:
#' [1] codon_number [2] codon_type [3] aa_type [4] observed_count [5] bias_coefficient [6] corrected_count.
#' @param count_type Options: "observed_count", "corrected_count".
#' @details Stalling bias correction is performed at the codon level but differential translational efficiency analysis
#' is ususally performed at transcript level. This function sums up codon level counts (observed or corrected) for each transcript.
#' @examples
#' rpf_observed_sum_LMCN <- codon2transcript(tr_codon_bias_coeff_loess_corrected_count_LMCN$tr_codon_read_count_loess_corrected, "observed_count")
#' rpf_corrected_sum_LMCN <- codon2transcript(tr_codon_bias_coeff_loess_corrected_count_LMCN$tr_codon_read_count_loess_corrected, "corrected_count")
#' @return A data frame where the first column is transcript IDs and the remaining columns contain per transcript read counts for all samples.
#' @export
codon2transcript <- function(tr_codon_read_count_loess_corrected_list, count_type) {
  count_sum <- as.data.frame(sapply(tr_codon_read_count_loess_corrected_list, function(x) sapply(x, function(y) sum(y[count_type]))))

  count_sum$transcript <- rownames(count_sum)
  w <- dim(count_sum)[2]
  count_sum <- count_sum[,c(w,1:(w-1))]
  count_sum <- count_sum[order(count_sum$transcript),]
  rownames(count_sum) <- NULL

  total_counts <- as.data.frame(rowSums(count_sum[,-1]) )
  rownames(total_counts) <- count_sum$transcript

  empty_transcripts <- c()

  for (transcript in count_sum$transcript){
    if (total_counts[transcript,] == 0) {
      empty_transcripts <- c(empty_transcripts, transcript)
    }
  }

  if (length(empty_transcripts) > 0) {
    warning(paste('There are',length(empty_transcripts), 'transcripts that have 0 counts across all samples.',
    'Use Ribolog::min_count_filter to remove them before translational efficiency testing.'))
  }

  return(count_sum)
}


#' @title plot_mirrors_CELP
#' @description Plot the bias coefficient for one transcript in one sample. Not exported; used only
#' internally by \code{\link{visualize_CELP}}, which pre-computes consistent \code{ylim_low_i}/\code{ylim_up_i}
#' across all of a transcript's samples before calling this once per sample.
#' @param x Data frame containing CELP output for a trancript in one sample
#' @param ylim_low_i Lower bound on y axis
#' @param ylim_up_i Upper bound on y axis
#' @param xlim_low_i Lower bound on x axis
#' @param xlim_up_i Upper bound on x axis
#' @param sample Name of the sample to be plotted
#' @noRd
plot_mirrors_CELP <- function(x, ylim_low_i, ylim_up_i, xlim_low_i = NULL, xlim_up_i = NULL, sample){
  plot(x$codon_number, y = x$observed_count, type="h",
       xlab = "Codon number", ylab = "Read counts", main = sample,
       ylim = c(ylim_low_i, ylim_up_i), xlim = c(xlim_low_i, xlim_up_i))
  lines(x$bias_coefficient, col = "red")
  lines((-1)*(x$corrected_count), col = "darkorchid1", type = "h")
}


#' @title visualize_CELP
#' @description Function to visualize translational stalling (CELP bias) overlaid on observed and corrected read counts.
#' @param tr_codon_read_count_loess_corrected_list A list of codon level read counts for all samples and transcripts.
#' It is the second element of a tr_codon_bias_coeff_corrected_count object produced by \code{\link{CELP_bias}}.
#' It has the following structure:
#' list$<sample.name>$<transcript.ID> data.frame:
#' [1] codon_number [2] codon_type [3] aa_type [4] observed_count [5] bias_coefficient [8] corrected_count.
#' @param transcript Name of the transcript to be plotted
#' @param panel_rows Number of rows in the case of plotting multiple samples on one page. Default: 1.
#' @param panel_cols Number of columns in the case of plotting multiple samples on one page. Default: 1.
#' @param from_codon Plot starts from this codon. Use this and to_codon to zoom in on particular regions of the transcript. Default: NULL (plot starts at the start codon).
#' @param to_codon Plot ends with this codon. Use this and from_codon to zoom in on particular regions of the transcript. Default: NULL (plot stops at the stop codon).
#' @param outfile Path and name of the output pdf file. If it is not provided, plots will be printed to standard output. Default: NULL.
#' @details This function plots the CELP bias coefficient as a curve overlaid on barplots of observed read counts upward
#' (positive y) and corrected read counts downward (in the nominal negative y range). This allows visual inspection of the
#' prominent bias positions and a comparison of read count heterogeneity along the transcript before and after
#' CELP bias correction.
#' @examples
#' visualize_CELP(tr_codon_bias_coeff_loess_corrected_count_LMCN$tr_codon_read_count_loess_corrected, "ENST00000000233", "<file.path>/ENST00000000233.CELP.bias.plots.pdf")
#' visualize_CELP(tr_codon_bias_coeff_loess_corrected_count_LMCN$tr_codon_read_count_loess_corrected, "ENST00000000233", panel_rows = 2, panel_cols = 4, "<file.path>/ENST00000000233.CELP.bias.all.in.one.page.plots.pdf")
#' @export
visualize_CELP <- function(tr_codon_read_count_loess_corrected_list, transcript, panel_rows = 1, panel_cols = 1, from_codon = NULL, to_codon = NULL, outfile=NULL){
  x_tr <- lapply(tr_codon_read_count_loess_corrected_list, function(y) y[[transcript]])
  ylim_up <- max(unlist(lapply(x_tr, function(y) max(y$observed_count))))
  ylim_low <- (-1) * max(unlist(lapply(x_tr, function(y) max(y$corrected_count))))

  if (is.null(outfile)){
    par(mfrow = c(panel_rows, panel_cols))
  } else {
    pdf(outfile, height = 10, width = 20)
  }

  for (s in names(x_tr)) {
    plot_mirrors_CELP(x_tr[[s]], ylim_low_i = ylim_low, ylim_up_i = ylim_up, xlim_low_i = from_codon, xlim_up_i = to_codon, s)
  }

  if (!is.null(outfile)) {
    dev.off()
    sprintf("PDF (%s) created and saved", outfile)
  }
}


codon_usage_psite_rW <- function(data, annotation, sample, site = "psite",
                              fastapath = NULL, fasta_genome = TRUE,
                              refseq_sep = NULL, bsgenome = NULL, gtfpath = NULL,
                              txdb = NULL, dataSource = NA, organism = NA,
                              transcripts = NULL, frequency_normalization = TRUE,
                              codon_values = NULL, label_scatter = FALSE,
                              label_number = 64, label_aminoacid = FALSE) {

  if(site != "psite" & site != "asite" & site != "esite"){
    cat("\n")
    stop("parameter site must be either \"psite\", \"asite\" or \"esite\" \n\n")
  }

  if(length(sample) > 2){
    cat("\n")
    stop("max two samples can be specified \n\n")
  }

  if(length(codon_values) != 0){
    rownames(codon_values) <- as.character(codon_values$codon)
    if (nrow(codon_values) < 64 | length(unique(rownames(codon_values))) < 64){
      cat("\n")
      stop("number of different triplets in codon_values < 64. At least one codon is missing\n\n")
    } else {
      if (length(unique(rownames(codon_values))) > 64){
        cat("\n")
        stop("number of different triplets in codon_values > 64. Too many codons\n\n")
      }
    }
  }

  if(length(sample) == 2 & length(codon_values) != 0){
    cat("\n")
    warning("codon_values will be ingnored: two samples are specified\n")
    codon_values = NULL
  }

  if((sum(lapply(data[sample], function(x) (gsub("site", "_site_codon", site) %in% colnames(x))) == TRUE) < length(sample)) |
     ((sum(lapply(data[sample], function(x) (gsub("site", "_site_codon", site) %in% colnames(x))) == TRUE) == length(sample)) &
      (frequency_normalization == TRUE | frequency_normalization == T))){

    if(length(fastapath) == 0 & length(bsgenome) == 0){
      cat("\n")
      if(sum(lapply(data[sample], function(x) (gsub("site", "_site_codon", site) %in% colnames(x))) == TRUE) < length(sample)){
        stop(paste0("unable to add ", gsub("site", "_site_codon", site), " column. Either fastpath or bsgenome must be specified\n\n"))
      } else {
        warning("no nucleotide sequences provided. Either fastpath or bsgenome must be specified. Non-normalized codon usage indexes will be returned\n")
        frequency_normalization = FALSE
      }
    }

    if(((length(fastapath) != 0 & (fasta_genome == TRUE | fasta_genome == T)) |
        length(bsgenome) != 0) &
       length(gtfpath) == 0 & length(txdb) == 0){
      cat("\n")
      stop("genome annotation file not specified. Either gtfpath or txdb object must be specified\n\n")
    }

    if(length(fastapath) != 0 & length(bsgenome) != 0){
      cat("\n")
      warning("both fastapath and bsgenome are specified. Only fastapath will be considered\n")
      bsgenome = NULL
    }

    if(length(gtfpath) != 0 & length(txdb) != 0){
      cat("\n")
      warning("both gtfpath and txdb are specified. Only gtfpath will be considered\n")
      txdb = NULL
    }

    if((length(gtfpath) != 0 | length(txdb) != 0) &
       ((length(fastapath) == 0 & length(bsgenome) == 0) |
        (length(fastapath) != 0 & (fasta_genome == FALSE | fasta_genome == F)))){
      cat("\n")
      stop("genome annotation file specified but no sequences from genome assembly provided\n\n")
    }

    if(length(gtfpath) != 0 | length(txdb) != 0){
      if(length(gtfpath) != 0){
        path_to_gtf <- gtfpath
        suppressWarnings(txdbanno <- txdbmaker::makeTxDbFromGFF(file = path_to_gtf,
                                                                      format = "gtf",
                                                                      dataSource = dataSource,
                                                                      organism = organism))
      } else {
        if(txdb %in% rownames(installed.packages())){
          library(txdb, character.only = TRUE)
        } else {
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
          BiocManager::install(txdb, update = FALSE, ask = FALSE)
          library(txdb, character.only = TRUE)
        }
        txdbanno <- get(txdb)
      }
    }

    if(length(fastapath) != 0 | length(bsgenome) != 0){
      if(length(fastapath) != 0) {
        if(fasta_genome == TRUE | fasta_genome == T){
          temp_sequences <- Biostrings::readDNAStringSet(fastapath, format = "fasta", use.names = TRUE)
          if(length(refseq_sep) != 0){
            names(temp_sequences) <- tstrsplit(names(temp_sequences), refseq_sep, fixed = TRUE, keep = 1)[[1]]
          }
          exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx", use.names = TRUE))
          exon <- data.table::as.data.table(exon[unique(names(exon))])
          sub_exon_plus <- exon[as.character(seqnames) %in% names(temp_sequences) & strand == "+"]
          sub_exon_minus <- exon[as.character(seqnames) %in% names(temp_sequences) & strand == "-"
                                 ][, new_end := Biostrings::width(temp_sequences[as.character(seqnames)]) - start + 1
                                   ][, new_start := Biostrings::width(temp_sequences[as.character(seqnames)]) - end + 1]

          seq_dt_plus <- sub_exon_plus[, nt_seq := "emp"
                                       ][, nt_seq := as.character(Biostrings::subseq(temp_sequences[as.character(seqnames)],
                                                                                     start = start,
                                                                                     end = end))
                                         ][, list(seq = paste(nt_seq, collapse = "")), by = group_name]

          revcompl_temp_sequences <- Biostrings::reverseComplement(temp_sequences)
          seq_dt_minus <- sub_exon_minus[, nt_seq := "emp"
                                         ][, nt_seq := as.character(Biostrings::subseq(revcompl_temp_sequences[as.character(seqnames)],
                                                                                       start = new_start,
                                                                                       end = new_end))
                                           ][, list(seq = paste(nt_seq, collapse = "")), by = group_name]

          sequences <- Biostrings::DNAStringSet(c(seq_dt_plus$seq, seq_dt_minus$seq))
          names(sequences) <- c(unique(sub_exon_plus$group_name), unique(sub_exon_minus$group_name))
        } else {
          sequences <- Biostrings::readDNAStringSet(fastapath, format = "fasta", use.names = TRUE)
          if(length(refseq_sep) != 0){
            names(sequences) <- tstrsplit(names(sequences), refseq_sep, fixed = TRUE, keep = 1)[[1]]
          }
        }
      } else {
        if(bsgenome %in% installed.genomes()){
          library(bsgenome, character.only = TRUE)
        } else {
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
          BiocManager::install(bsgenome, update = FALSE, ask = FALSE)
          library(bsgenome, character.only = TRUE)
        }
        sequences <- GenomicFeatures::extractTranscriptSeqs(get(bsgenome), txdbanno, use.names = T)
      }
    }

    for(samp in sample){
      if(!(gsub("site", "_site_codon", site) %in% colnames(data[[samp]]))){
        if(site == "psite" & !("p_site_codon" %in% colnames(data[[samp]]))){
          data[[samp]] <- data[[samp]][, p_site_codon := as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)],
                                                                                         start = data[[samp]]$psite,
                                                                                         end = data[[samp]]$psite + 2))]
        }
        if(site == "asite" & !("a_site_codon" %in% colnames(data[[samp]]))){
          data[[samp]] <- data[[samp]][, a_site_codon := as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)],
                                                                                         start = data[[samp]]$psite + 3,
                                                                                         end = data[[samp]]$psite + 5))]
        }
        if(site == "esite" & !("e_site_codon" %in% colnames(data[[samp]]))){
          data[[samp]] <- data[[samp]][, e_site_codon := as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)],
                                                                                         start = data[[samp]]$psite - 3,
                                                                                         end = data[[samp]]$psite - 1))]
        }
      }
    }
  }

  l_transcripts <- as.character(annotation[l_cds > 0 & l_cds %% 3 == 0, transcript])

  cod_aa <- data.table(codon=c("GCC", "GCG", "GCU", "GCA", "AGA", "CGG", "AGG", "CGA", "CGC", "CGU", "AAC", "AAU", "GAC", "GAU", "UGC", "UGU", "CAA", "CAG", "GAG", "GAA", "GGC", "GGU", "GGA", "GGG", "CAC", "CAU", "AUA", "AUC", "AUU", "CUG", "CUA", "UUA", "CUU", "UUG", "CUC", "AAA", "AAG", "AUG", "UUC", "UUU", "CCG", "CCC", "CCU", "CCA", "AGC", "UCG", "UCU", "UCA", "UCC", "AGU", "UAG", "UAA", "UGA", "ACA", "ACC", "ACG", "ACU", "UGG", "UAU", "UAC", "GUA", "GUG", "GUU", "GUC"),
                       aa=c("A", "A", "A", "A", "R", "R", "R", "R", "R", "R", "N", "N", "D", "D", "C", "C", "Q", "Q", "E", "E", "G", "G", "G", "G", "H", "H", "I", "I", "I", "L", "L", "L", "L", "L", "L", "K", "K", "M", "F", "F", "P", "P", "P", "P", "S", "S", "S", "S", "S", "S", "*", "*", "*", "T", "T", "T", "T", "W", "Y", "Y", "V", "V", "V", "V"))
  cod_lev <- gsub("U", "T", cod_aa$codon)

  if (length(transcripts) == 0) {
    c_transcript <- l_transcripts
  } else {
    c_transcript <- intersect(l_transcripts, transcripts)
  }

  if(frequency_normalization == TRUE | frequency_normalization == T){
    if(setequal(names(sequences), as.character(annotation$transcript)) == FALSE){
      exc_seq <- length(setdiff(names(sequences), as.character(annotation$transcript)))
      exc_anno <- length(setdiff(as.character(annotation$transcript), names(sequences)))

      if(exc_seq > 0){
        cat("\n")
        warning(sprintf("more reference sequences (from FASTA or BSgenome) than transcript IDs (from annotation data table)\n  %s reference sequences discarded", exc_seq))
      }

      if(exc_anno > 0){
        cat("\n")
        warning(sprintf("more transcript IDs (from annotation data table) than sequences (from FASTA or BSgenome)\n  %s reference sequences discarded", exc_seq))
      }
    }

    c_transcript <- intersect(c_transcript, names(sequences))
    sub_sequences <- sequences[c_transcript]
    cds_biost <- Biostrings::subseq(sub_sequences,
                                    start = annotation[transcript %in% names(sub_sequences), l_utr5] + 1,
                                    end = annotation[transcript %in% names(sub_sequences), l_utr5] +
                                      annotation[transcript %in% names(sub_sequences), l_cds])

    seq_freq <- (Biostrings::trinucleotideFrequency(cds_biost, step = 3,
                                                    as.prob = TRUE,
                                                    with.labels = TRUE,
                                                    simplify.as = "collapsed")) * 1000
    names(seq_freq) <- gsub("T", "U", names(seq_freq))
  }

  if(exists("norm_table")){
    rm(norm_table)
  }
  for(samp in sample) {
    dt <- data[[samp]][as.character(transcript) %in% c_transcript & psite_from_start %% 3 == 0]

    if(site == "psite"){
      dt <- dt[psite_region == "cds"]
      temp_table <- data.table(table(factor(dt$p_site_codon, levels = cod_lev)))
    } else {
      if(site == "asite"){
        dt <- dt[psite_from_start >= -3 & psite_from_stop <= -3]
        temp_table <- data.table(table(factor(dt$a_site_codon, levels = cod_lev)))
      } else {
        dt <- dt[psite_from_start >= 3 & psite_from_stop <= 3]
        temp_table <- data.table(table(factor(dt$e_site_codon, levels = cod_lev)))
      }
    }
    colnames(temp_table) <- c("codon", "raw_value")

    temp_table <- temp_table[, codon := gsub("T", "U", codon)]

    if(frequency_normalization == TRUE | frequency_normalization == T){
      temp_table <- temp_table[, normalized_value := raw_value / seq_freq[codon]]
      colplot <- "normalized_value"
    } else {
      colplot <- "raw_value"
    }

    temp_table <- temp_table[, plot_value := get(colplot) - min(get(colplot))
                             ][, plot_value := plot_value / max(plot_value)]

    if(!exists("norm_table")){
      norm_table <- temp_table
    } else {
      if(frequency_normalization == TRUE | frequency_normalization == T){
        norm_table[, "comp_normalized_value" := temp_table$normalized_value]
      }
      norm_table[, c("comp_raw_value", "comp_plot_value") := list(temp_table$raw_value, temp_table$plot_value)]
    }
  }

  norm_table <- norm_table[, class := "cds"
                           ][codon == "AUG", class := "start"
                             ][codon %in% c("UAA", "UGA", "UAG"), class := "stop"
                               ][, class := factor(class, levels = c("start", "cds", "stop"),
                                                   labels=c("Start codon", "cds", "Stop codon"))
                                 ][cod_aa, on = "codon"]

  if(length(sample) == 1){
    output <- list()
    if(frequency_normalization == TRUE | frequency_normalization == T){
      output[["dt"]] <- norm_table[, c("codon",  "aa", "class", "raw_value", "normalized_value", "plot_value")]
    } else {
      output[["dt"]] <- norm_table[, c("codon",  "aa", "class", "raw_value", "plot_value")]
    }

    if(length(codon_values) != 0){
      codon_values <- codon_values[, list(codon, value)]
      setnames(codon_values, old = c("codon", "value"), new =  c("codon", "comp_values"))
      codon_values[, codon := gsub("T", "U", codon)]
      norm_table <- norm_table[codon_values, on = "codon"
                               ][, comp_plot_value := comp_values - min(comp_values)
                                 ][, comp_plot_value := comp_plot_value / max(comp_plot_value)]

      output[["dt"]] <- cbind(output[["dt"]], norm_table[, c("comp_values", "comp_plot_value")])
      setnames(output[["dt"]], old = c("comp_values", "comp_plot_value"), new = c("user_value", "plot_user_value"))
      nc <- ncol(output[["dt"]])
      output[["dt"]] <- output[["dt"]][, c(1:(nc - 3), nc -1 , nc - 2, nc), with = FALSE]

      plotnamex <- "Codon usage index"
      plotnamey <- "User value"
    }
  } else {
    output <- list()
    if(frequency_normalization == TRUE | frequency_normalization == T){
      output[["dt"]] <- norm_table[, c("codon", "aa", "class", "raw_value", "comp_raw_value",
                                       "normalized_value", "comp_normalized_value", "plot_value", "comp_plot_value")]
      setnames(output[["dt"]],
               old = c("normalized_value", "comp_normalized_value"),
               new = paste0("normalized_value_", c(sample[1], sample[2])))
    } else {
      output[["dt"]] <- norm_table[, c("codon", "aa", "class", "raw_value", "comp_raw_value",
                                       "plot_value", "comp_plot_value")]
    }

    setnames(output[["dt"]],
             old = c("raw_value", "comp_raw_value", "plot_value", "comp_plot_value"),
             new = paste(rep(c("raw_value", "plot_value"),each=2), c(sample[1], sample[2]), sep = "_"))

    plotnamex <- sample[1]
    plotnamey <- sample[2]
  }

  oldw <- getOption("warn")
  options(warn=-1)

  bs <- 30
  plot_list <- list()
  i = 1
  for(samp in sample){
    plot_col <- ifelse(i == 1, "plot_value", "comp_plot_value")
    i <- i + 1

    norm_table <- norm_table[order(get(plot_col))
                             ][, codon := factor(codon, levels = codon)]

    colour_codon <- ifelse(norm_table$codon == "AUG", "#104ec1",
                           ifelse(norm_table$codon %in% c("UAA", "UGA", "UAG"),
                                  "darkred", "gray40"))

    bp <- ggplot(norm_table, aes_string(x = "codon", y = plot_col, fill = "class")) +
      geom_bar(stat = "identity", alpha = 0.9) +
      scale_fill_manual(name = "", breaks=c("Start codon","Stop codon"), values = c("#104ec1", "gray60", "darkred")) +
      theme_bw(base_size = bs) +
      theme(legend.position = "top", legend.margin=margin(0,0,0,0), legend.box.margin=margin(5,0,-15,0)) +
      theme(legend.text = element_text(margin = margin(l = -12, unit = "pt"))) +
      scale_x_discrete("Codon") +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5, size = bs * 0.5)) +
      geom_text(aes(label = aa), vjust = -0.5, size = bs/6) +
      theme(axis.text.x = element_text(colour = colour_codon), panel.grid.major.x = element_blank(),
                                       panel.grid.minor.y = element_blank()) +
      scale_y_continuous("Usage index", limits = c(0,1.075), breaks = c(0,0.25,0.5,0.75,1))
    plot_list[[paste0("plot_", samp)]] <- bp
  }

  if(length(sample) == 1){
    output[["plot"]] <- plot_list[[paste0("plot_", sample)]]
  }

  if(length(codon_values) != 0 | length(sample) == 2){

    norm_table <- norm_table[order(plot_value)
                             ][, codon := factor(codon, levels = codon)]

    correlation <- round(cor(norm_table$plot_value, norm_table$comp_plot_value), 3)

    bs <- 25
    pcomp <- ggplot(norm_table,aes(x = plot_value, y = comp_plot_value, colour = class)) +
      geom_smooth(method = "lm", se=T, color="gray80", fill="gray80", linetype = 1, formula = y ~ x, level = 0.99,  fullrange = TRUE) +
      geom_point(alpha = 0.9, size = bs * 0.14) +
      scale_colour_manual(name = "", breaks = c("Start codon","Stop codon"), values = c("#104ec1", "gray40", "darkred")) +
      theme_bw(base_size = bs) +
      theme(legend.position = "top", legend.margin=margin(0,0,0,0), legend.box.margin=margin(5,0,-15,0)) +
      theme(legend.text = element_text(margin = margin(l = -12, unit = "pt"))) +
      theme(panel.grid.minor.y = element_blank(), panel.grid.minor.x = element_blank()) +
      scale_x_continuous(name = plotnamex, limits = c(-0.3,1.3), breaks = c(0,0.25,0.5,0.75,1), expand = c(0,0)) +
      scale_y_continuous(name = plotnamey, limits = c(-0.3,1.3), breaks = c(0,0.25,0.5,0.75,1), expand = c(0,0)) +
      coord_cartesian(xlim = c(-0.05,1.05), ylim = c(-0.05,1.05)) +
      annotate("text", x = 1, y = 0, label = paste0("R=",correlation), vjust = -0.2, size = bs * 0.2, hjust = 1, color = "black")

    if (label_scatter == T || label_scatter == TRUE) {
      if (label_number != 64){
        fit <- lm(norm_table$comp_plot_value ~ norm_table$plot_value)
        outlier_tab <- data.table(predict.lm(fit, interval = "confidence", level = 0.95)
        )[, codon := norm_table$codon
          ][, comp_plot_value := norm_table$comp_plot_value
            ][comp_plot_value < lwr | comp_plot_value > upr]
        outlier_cod <- as.character(outlier_tab[, max_dist := min(abs(comp_plot_value - lwr), abs(comp_plot_value - upr)),
                                                by = 1:nrow(outlier_tab)
                                                ][order(-max_dist)
                                                  ][1:label_number, codon])
        lab_table <- norm_table[, codon_out := ""
                                 ][as.character(codon) %in% outlier_cod, codon_out := codon
                                   ][, aa_out := ""
                                     ][codon_out != "", aa_out := aa]

        if (label_aminoacid == T || label_aminoacid == TRUE) {
          label_col <- "aa_out"
        } else {
          label_col <- "codon_out"
        }
      } else {
        lab_table <- norm_table
        if (label_aminoacid == T || label_aminoacid == TRUE) {
          label_col <- "aa"
        } else {
          label_col <- "codon"
        }
      }

      pcomp <- pcomp +
        ggrepel::geom_text_repel(data = lab_table,
                                 aes_string("plot_value", "comp_plot_value", label = as.character(label_col)), show.legend = F)
    }

    if(length(sample) == 2){
      output[[paste0("plot_", sample[1])]] <- plot_list[[paste0("plot_", sample[1])]]
      output[[paste0("plot_", sample[2])]] <- plot_list[[paste0("plot_", sample[2])]]
    }

    output[["plot_comparison"]] <- pcomp
  }

  options(warn = oldw)
  return(output)
}



#' @title codon_barplot
#' @description Function to visualise the codon usage in every sample
#' @param reads_psite_list Output object of a psite_info_rW function
#' @param annotation A dataframe denoting the annotations
#' @param fasta_path A path to the fasta file
#' @param outfile file name to output visualisations
#' @return Barplots for each sample
#' @export

codon_barplot <- function(reads_psite_list, annotation, fasta_path, outfile=NULL){

  if (!is.null(outfile)) { pdf(outfile)}

  for (sample_i in names(reads_psite_list)){
    output <- codon_usage_psite_rW(reads_psite_list, annotation, sample = c(sample_i),
                                fastapath = fasta_path, fasta_genome = FALSE, frequency_normalization = FALSE)
    print(output[["plot"]]  + ggtitle(sample_i) + theme(plot.title = element_text(hjust = 0.5)))
  }

  if (!is.null(outfile)) {
    dev.off()
    sprintf("PDF (%s) created and saved", outfile)
  }
}



#' @title codon_comparative_scatterplot
#' @description Function to visualise the comparative codon usage for every sample
#' @param reads_psite_list Output object of a psite_info_rW function
#' @param annotation A dataframe denoting the annotations
#' @param fasta_path A path to the fasta file
#' @param outfile file name to output visualisations
#' @return Barplots for each sample
#' @export

codon_comparative_scatterplot <- function(reads_psite_list, annotation, fasta_path, outfile=NULL){

  if (!is.null(outfile)) { pdf(outfile)}

  for (sample_i in names(reads_psite_list)){

     for (sample_2 in names(reads_psite_list)[names(reads_psite_list) != sample]){

    output <- codon_usage_psite_rW(reads_psite_list, annotation, sample = c(sample_i, sample_2),
                                fastapath = fasta_path, fasta_genome = FALSE, frequency_normalization = FALSE)

    options(repr.plot.width = 10, repr.plot.height = 10)
    print(output[["plot_comparison"]])

    }
  }

  if (!is.null(outfile)) {
    dev.off()
    sprintf("PDF (%s) created and saved", outfile)
  }
}
